version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    env_file:
      - .env
