version: '3.8'

services:
  app:
    build:
      context: .
      args:
        HF_AUTH_TOKEN: ${HUGGINGFACE_TOKEN}
    ports:
      - "5000:5000"
    environment:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
